### ISSUE TITLE
capnap error when I tried to run basic gedis tests

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/digitalmeX#251]
**steps:**
```python
 j.servers.gedis.test()   
```

**Result**
```
JSX> j.servers.gedis.test()                                                                                                                                                                                        
Sun 05 10:25:05 JSBase.py        - 482 - j.servers.gedis:gedisfactory       : ##: TEST RUN: BASIC
Sun 05 10:25:05 JSBase.py        - 482 - j.servers.gedis:gedisfactory       : ##: TEST RUN: 1_BASIC.PY
no server running on /tmp/tmux-0/default
no server running need to start
++ '[' start == kill ']'
++ tmux -f /sandbox/cfg/.tmux.conf has-session
no server running on /tmp/tmux-0/default
++ '[' 1 -eq 1 ']'
++ echo 'no server running need to start'
++ tmux -f /sandbox/cfg/.tmux.conf new -s main -d 'bash --rcfile /sandbox/bin/env_tmux_detach.sh'
++ '[' start '!=' start ']'
main: 1 windows (created Sun May  5 10:25:07 2019) [80x24]
Sun 05 10:25:08 Tmux.py          -  85 - j.tools.tmux:tmux                  : tmux server is running
Sun 05 10:25:10 StartupCMD.py    - 133 - startupcmd:startupcmd              : IS RUNNING gedis_test
Sun 05 10:25:10 1_basic.py       -  30 - j.servers.gedis:gedisfactory       : gedis server '8888' started
[*] testing echo
Sun 05 10:25:11 GedisClient.py   - 133 - j.clients.gedis:gedisclient        : redisclient: 127.0.0.1:8888 
- done
[*] testing set with schemas
[1] schema_in as schema url
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/DigitalMe/servers/gedis/GedisFactory.py", line 56, in test
    self._test_run(name=name)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 465, in _test_run
    res = self.__test_run(name=name, obj_key=obj_key, die=die, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 503, in __test_run
    self.__test_run(name=bname, obj_key=obj_key, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 520, in __test_run
    res = method(self=self, **kwargs)
  File "/sandbox/lib/jumpscale/DigitalMe/servers/gedis/tests/1_basic.py", line 45, in main
    wallet_out1 = client.actors.painter.example1(addr="testaddr")
  File "/sandbox/var/codegen/painter.py", line 81, in example1
    res2 = schema_out.get(capnpbin=res)
  File "/sandbox/lib/jumpscale/Jumpscale/data/schema/Schema.py", line 294, in get
    obj = self.objclass(schema=self, data=data, capnpbin=capnpbin, model=model)
  File "/sandbox/lib/jumpscale/Jumpscale/data/schema/DataObjBase.py", line 18, in __init__
    self._load_from_data(data=data, capnpbin=capnpbin, keepid=False, keepacl=False)
  File "/sandbox/lib/jumpscale/Jumpscale/data/schema/DataObjBase.py", line 30, in _load_from_data
    self._cobj_ = self._capnp_schema.from_bytes_packed(capnpbin)
  File "capnp/lib/capnp.pyx", line 3061, in capnp.lib.capnp._StructModule.from_bytes_packed
  File "capnp/lib/capnp.pyx", line 3498, in capnp.lib.capnp._PackedMessageReaderBytes.__init__
capnp.lib.capnp.KjException: kj/io.c++:73: failed: expected result.size() > 0; Premature EOF
stack: 0x7f5520489ce3 0x7f55204eb0b4 0x7f55204885a6 0x7f552048969b 0x7f552037c494 0x555421 0x7f5520367585 0x5a730c 0x503073 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x501b2e 0x591461 0x54b813 0x555421 0x5a730c 0x503073 0x507641 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x502540 0x502f3d 0x507641 0x504c28

kj/io.c++:73: failed: expected result.size() > 0; Premature EOF
stack: 0x7f5520489ce3 0x7f55204eb0b4 0x7f55204885a6 0x7f552048969b 0x7f552037c494 0x555421 0x7f5520367585 0x5a730c 0x503073 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x501b2e 0x591461 0x54b813 0x555421 0x5a730c 0x503073 0x507641 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x502540 0x502f3d 0x507641 0x504c28
JSX>  
```

**Hint**
I tried to do the `example1` manually and It worked
```python
In [15]: j.data.schema.get(url='jumpscale.example.wallet')                                             
Out[15]: 
prop:jwt                       string
prop:addr                      string
prop:ipaddr                    ipaddr
prop:email                     string
prop:username                  string

In [16]: sch = j.data.schema.get(url='jumpscale.example.wallet')                                       

In [17]: w = sch.new()                                                                                 

In [18]: w.addr = '7amda'                                                                              

In [19]: w                                                                                             
Out[19]: 
addr = "7amda"
email = ""
ipaddr = "0.0.0.0"
jwt = ""
username = ""

In [20]:     

```

**Comment by despiegk** [comment]
no longer relevant on newest branch
