### ISSUE TITLE
Creating a reservation for capacity gives an error with GedisClientFactory

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/digitalmeX#38]
Linking this issue from https://github.com/threefoldtech/jumpscaleX/issues/240

**Comment by abom** [comment]
It seems like this issue has been resolved, but i'm getting a new error now (related to notary.grid.tf).
```

JSX> result = w.capacity.reserve_zos_vm( 
   2     email='ghanema@codescalers.com', # the email on which you will received the connection information 
   3     threebot_id='ghanem2.example', # your threebot id, it can be any of the names you gave to your 3bot 
   4     location='vcc', # name of the farm or node id where to deploy the workload 
   5     size=1) # each workload have a different size available                                                                                      
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainCapacity.py", line 131, in reserve_zos_vm
    return self._process_reservation(reservation, threebot_id, source=source, refund=refund)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainCapacity.py", line 152, in _process_reservation
    response = self._notary_client.register(threebot_id, signature.message, signature.signature)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/blockchain/tfchain/TFChainCapacity.py", line 26, in _notary_client
    self._notary_client_ = c.actors.notary_actor
  File "/sandbox/lib/jumpscale/DigitalMe/clients/gedis/GedisClient.py", line 70, in actors
    assert self.ping()
  File "/sandbox/lib/jumpscale/DigitalMe/clients/gedis/GedisClient.py", line 51, in ping
    test = self._redis.execute_command("ping")
  File "/root/.local/lib/python3.6/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/root/.local/lib/python3.6/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/root/.local/lib/python3.6/site-packages/redis/connection.py", line 497, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to notary.grid.tf:5000. Connection refused.

Error 111 connecting to notary.grid.tf:5000. Connection refused.


```

**Comment by abom** [comment]
Seems like `connection refused` error is resolved https://github.com/threefoldtech/jumpscaleX/issues/330
